### ISSUE TITLE
Default file generated as drop-in 00-ansible.conf

### ISSUE THREAD

**Issue by skwde** [linux-system-roles/ssh#100]
I expect following snippet to produce the default config for RHEL9:

```yml
- name: Test
  hosts: rhel9
  gather_facts: false
  tasks:
    - name: Generate ssh RHEL9
      become: true
      block:
        - name: Handle default ssh_config for RHEL9
          ansible.builtin.include_role:
            name: fedora.linux_system_roles.ssh
```

Instead it creates a drop in file `00-ansible.conf` with the defaults. Why is that?

The fix I found for RHEL8 (<https://github.com/linux-system-roles/ssh/issues/89>), namely setting the variable `ssh: {}` does not work here.
It also doesn't help to set the variable `ssh_skip_defaults: false`...

Now the fix seems to be to explicitly set `ssh_drop_in_name: null`...

It is really not very convenient to do trial and error all the time for simple stuff like having a default config generated.

Can you please document with an example playbook how one should generate the default config and an additional drop in config.
