### ISSUE TITLE
Confusing drop-in behavior

### ISSUE THREAD

**Issue by skwde** [linux-system-roles/ssh#89]
When using drop-in names the behaviour is unexpected:

```yml
- name: Test
  hosts: rhel8
  gather_facts: false
  become: true
  roles:
    - role: fedora.linux_system_roles.ssh
      vars:
        ssh_skip_defaults: false
        ssh_config_file: '~/src/tests/ssh/ssh_config_RHEL8_test'
    - role: fedora.linux_system_roles.ssh
      vars:
        ssh_skip_defaults: true
        ssh_config_file: '~/src/tests/ssh/ssh_config.d_RHEL8_test/99-some-test.conf'
        ssh:
          Match:
            - Condition: "User {{ user_list | join(',') }}"
              SendEnv: 'SOME_VAR'

  vars:
    ssh_config_owner: 'user'
    ssh_config_group: 'user'
    ssh_config_mode: '0600'
    user_list:
      - 'user1'
      - 'user2'
```

This generates the default `~/src/tests/ssh/ssh_config_RHEL8_test` including the drop-in part

```
#
# Ansible managed
#
# system_role:ssh

Include /etc/ssh/ssh_config.d/*.conf
Match User user1,user2
  SendEnv SOME_ENV
```

and an `~/src/tests/ssh/ssh_config.d_RHEL8_test/99-some-test.conf` 

```
#
# Ansible managed
#
# system_role:ssh

Match User user1,user2
  SendEnv SOME_ENV

```

which is correct.

So it seems that the `ssh` variable defined in the second call is already available in the first call...

Is there a way around this?
